name: Collect Merge Queue Stats

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Collect merge queue statistics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p stats
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          OUTPUT_FILE="stats/merge_queue_${TIMESTAMP}.json"
          echo "Collecting merge queue statistics at $(date)..."
          python merge_queue_monitor.py -o "$OUTPUT_FILE"
          echo "STATS_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

          # Save the stats file and scripts to temporary location
          cp "$OUTPUT_FILE" /tmp/stats_temp.json
          cp generate_csv.py /tmp/
          cp generate_graphs.py /tmp/

      - name: Checkout stats-data branch
        run: |
          # Fetch stats-data branch if it exists
          git fetch origin stats-data:stats-data || echo "stats-data branch doesn't exist yet, will create it"

          # Check if stats-data branch exists locally or remotely
          if git show-ref --verify --quiet refs/heads/stats-data || git show-ref --verify --quiet refs/remotes/origin/stats-data; then
            git checkout stats-data
          else
            # Create new orphan branch
            git checkout --orphan stats-data
            git rm -rf .
            echo "# Merge Queue Statistics" > README.md
            echo "This branch contains automated merge queue statistics collected every 30 minutes." >> README.md
            echo "" >> README.md
            echo "Files are stored in \`stats/merge_queue_YYYYMMDD_HHMMSS.json\` format." >> README.md
            mkdir -p stats
            git add README.md
            git commit -m "Initialize stats-data branch"
          fi

      - name: Copy stats file to stats-data branch
        run: |
          # Restore the stats file from temporary location
          mkdir -p stats
          cp /tmp/stats_temp.json "${{ env.STATS_FILE }}"

          # Add and commit the new stats file
          git add "${{ env.STATS_FILE }}"
          git commit -m "Add stats: $(basename ${{ env.STATS_FILE }})"

      - name: Generate CSV and graph
        run: |
          # Restore scripts from temporary location
          cp /tmp/generate_csv.py .
          cp /tmp/generate_graphs.py .

          # Generate CSV from all stats files
          python generate_csv.py -o summarized.csv

          # Generate graph from CSV
          python generate_graphs.py -i summarized.csv -o .

          # Rename graph to match expected name
          mv prs_by_hour.png prs_by_hours.png

      - name: Update README with graph
        run: |
          cat > README.md << 'EOF'
          # Merge Queue Statistics

          This branch contains automated merge queue statistics collected every 30 minutes.

          ## Average PRs by Hour of Day (PST)

          ![PRs by Hour](prs_by_hours.png)

          ## Files

          - `summarized.csv` - CSV summary of all collected statistics
          - `prs_by_hours.png` - Graph showing average PRs by hour of day
          - `stats/merge_queue_YYYYMMDD_HHMMSS.json` - Individual JSON stats files
          EOF

      - name: Commit CSV, graph, and README
        run: |
          git add summarized.csv prs_by_hours.png README.md
          git commit -m "Update summary: CSV, graph, and README"

      - name: Push stats to stats-data branch
        run: |
          git push origin stats-data
